### PR TITLE
Use a multimodule maven organisation

### PR DESCRIPTION
**Pull request by victornoel**
- Change groupId to org.pac4j.jax-rs
 - Users should depend on jersey-pac4j or resteasy-pac4j
 - Add saveInSession parameter for callback endpoints

This simplifies and re-enforce the correctness of the testing and will ease the support of jersey 2.26 and other implementations (see #36 #30).

@pierre-l if you have some feedback on that? I will then do the same for branch 2.x and add a legacy dependency `org.pac4j.jax-rs-pac4j` for backward compatibility.

@leleuj once this is merged, `dropwizard-pac4j` will only depends on `jersey-pac4j`.

### CODE REVIEW

**Comment by victornoel** [comment]
@leleuj open question: should `jersey-pac4j` and `resteasy-pac4j` be under `org.pac4j.jax-rs` (like the rest of the submodules) or directly under `org.pac4j` (like `jax-rs-pac4j` and to keep things clear for users)?

**Comment by pierre-l** [comment]
@victornoel I'm not sure about the "test-tools" name I initially suggested, what do you think about "testing-tools" or just "testing"? Other than that, it seems pretty good to me. The part I liked the less in my commits for #36 won't be needed, I'm happy about this. I'll try to integrate this in our own project tomorrow in order to see if anything breaks. I'll let you know. Thanks!

**Comment by leleuj** [comment]
About the groupId, I would stick to `org.pac4j` for consistency with other pac4j libraries (in Play, we have two different libraries, one for Java and one for Scala, but both have the same groupId).
That said, it's not a major issue.

**Comment by victornoel** [comment]
> About the groupId, I would stick to org.pac4j for consistency with other pac4j libraries (in Play, we have two different libraries, one for Java and one for Scala, but both have the same groupId).
That said, it's not a major issue.

Ok, I will keep `org.pac4j.jax-rs` for the modules not meant to be used by users and `org.pac4j` for the dependencies the users require!

I will also rename the `test-tools` module to `testing`, it makes sense.

**Comment by victornoel** [comment]
I updated the PR, I will merge it later tonight except if you have other feedbacks :)

**Comment by pierre-l** [comment]
Nothing to report here.

**Pull request merged**
