### PR TITLE
#49 Unable to set expires attribute in Cookie

### PR DESCRIPTION
**Pull request by davoustp**

### CODE REVIEW

**Comment by davoustp** [comment]
Hi Jerome, any date for releasing this component?
Thx

**Comment by leleuj** [comment]
It's in progress. It should be available soon.

**Comment by davoustp** [comment]
Perfect! Thx a million. :-)

**Comment by leleuj** [comment]
There was an issue with the release. Will retry...

**Comment by leleuj** [comment]
My fault: the release was ok, the groupId has changed!

**Comment by davoustp** [comment]
Just grabbed the latest version - works with flying colors! Thx a lot.

**Pull request merged**
