### PR TITLE
WIP: Url prefix handling

### PR DESCRIPTION
**Pull request by victornoel**
Basically, the idea is that when running under a servlet container, the URLs as manipulated in the JAX-RS code (in `@Path` but also in the `@Pac4J*` annotations) should be relative to the context where the JAX-RS implementation is deployed.

For example if the servlet context is `/application` and on top of that, the servlet mapping path is `/api`, then all the URLs are prefixed in practice by `/application/api/`.
This is what is called `urlPrefix` in this PR.

When setting up the filters (under the responsibility of the user of the library, for example dropwizard-pac4j, and not of jax-rs-pac4j), the user can specify this prefix and design its application without worrying of the context.

Like this, if one specify `@Pac4JCallback(defaultUrl = "/user")`, the redirect will be prefixed by the `urlPrefix` as expected by the developer.

This is not totally complete, it applies to all parameters passed to the annotations only.
This is because pac4j does not take such concerns into account and thus the redirects that are done by the clients or things like that are not aware of the prefix. But at least, this is coherent in the realm of the jax-rs annotations!

@leleuj if you could give me a quick opinion on this before I merge it, it would be great, in case I missed something somewhere :)

### CODE REVIEW

**Comment by victornoel** [comment]
@evnm maybe you could also give your opinion about this, ultimately the objective is to set the urlPrefix in the Pac4jBundle with the concatenation of the rootPath and the applicationContextPath from the dropwizard configuration.

**Comment by evnm** [comment]
Makes sense to me. Servlet context paths are a common artifact of server implementations that use JAX-RS, so it's a good idea for `jax-rs-pac4j` to easily take them into account.

`dropwizard-pac4j` could infer the context path from the existing server configuration.

**Comment by victornoel** [comment]
@evnm yep, even if ultimately, I would prefer jax-rs-pac4j to be completely servlet agnostic, in either case, there is some kind of context url that exists. See pac4j/dropwizard-pac4j#11 for exactly what you are talking about at dropwizard level :)

**Comment by victornoel** [comment]
@leleuj if you validate, I will merge this :)

**Comment by leleuj** [comment]
I'll try to take a look at it this weekend or at worst, next Monday...

**Comment by leleuj** [comment]
I just have basic questions in fact:
1) why is this change not implemented in the `Pac4JSecurityFilterFeature` as well (maybe just the application context)?
2) Cannot we infer this `urlPrefix` somehow? It feels a bit strange to set it manually.

**Comment by victornoel** [comment]
To answer your questions @leleuj 
1) Two points:
   - `Pac4JSecurityFilterFeature` is for the `SecurityFilter`, which doesn't take any url as a parameter, so it makes no sense.
   - Actually,  this shows there is a problem more profoundly in pac4j because, there are urls manipulated in the `SecurityFilter`, but they are not provided to the filter, they are provided to the pac4j configuration.this whole business of prefix to the url could be done in pac4j ultimately I think,  but for now, from the pov of user experience in developing jax-rs applications, it makes a lot of sense to do it at least here.

2) We can't, because it's dependent on the context. You said yourself that for example in the J2E samples you have, you do want the servlet mapping path as part of the URL, but in jax-rs, usually you want both context path and servlet mapping path out of the way, or at least when used with dropwizard. But there is maybe other cases where one would want something different I guess... not sure, but to me it's dependent on the context where the jax-rs implementation is deployed. Furthermore, since in the long term jax-rs-pac4j would be servlet agnostic, this will be even more difficult to find a generic way to infer urlPrefix :)

**Comment by victornoel** [comment]
@leleuj actually you were right, jax-rs gives us the possibility to get this information, so no need for passing it as an option :)

I updated the PR, I think it's quite nice now, I will close pac4j/dropwizard-pac4j#11 which is now useless!

Still, it doesn't change the fact that it only covers the urls passed as parameters to the filters (or to the annotations).

**Comment by leleuj** [comment]
+1 Good to see we can do it with automatic configuration

**Pull request merged**
